spring.application.name=Inherit-Project-FSAD

spring.datasource.url=jdbc:mysql://localhost:3306/inherit_db
spring.datasource.username=root
spring.datasource.password=Pragna30@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8080
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration